# https://hub.docker.com/_/mysql
# Use root/example as user/password credentials
version: '3.5'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    volumes:
      - ./datadir:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d